#!/bin/bash



VIDEO_FOLDER="stc"
CAPTION_FILE="stc.csv"
OUTPUT_FOLDER="output/"
VIDEO_LIMIT=6
echo ${VIDEO_FOLDER} ${CAPTION_FILE} ${OUTPUT_FOLDER} ${VIDEO_LIMIT}
python generate_caption_webvid.py ${VIDEO_FOLDER} ${CAPTION_FILE} ${OUTPUT_FOLDER} ${VIDEO_LIMIT}